"""empty message

Revision ID: 614a85d9c771
Revises: f417491aadbf
Create Date: 2020-04-01 18:50:43.878390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614a85d9c771'
down_revision = 'f417491aadbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'seeking')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
